require:
  - standard/cop/block_single_line_braces

inherit_gem:
  standard: config/base.yml

inherit_from:
  - .rubocop/rubocop_rspec.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
    - 'bench/**/*'
  DisplayCopNames: true
  SuggestExtensions: false
  TargetRubyVersion: 2.7

Standard/BlockSingleLineBraces:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

RSpec/IdenticalEqualityAssertion:
  Exclude:
    - 'spec/fixtures/**/*'
